/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BLCol: typeof import('./src/components/BLCol.vue')['default']
    BLRow: typeof import('./src/components/BLRow.vue')['default']
    BLTag: typeof import('./src/components/BLTag.vue')['default']
    DayNight: typeof import('./src/components/DayNight.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    FsEstimatedVirtualList: typeof import('./src/components/FsEstimatedVirtualList.vue')['default']
    FsVirtualList: typeof import('./src/components/FsVirtualList.vue')['default']
    GWAudioPlayer: typeof import('./src/components/GWAudioPlayer.vue')['default']
    GWHeader: typeof import('./src/components/GWHeader.vue')['default']
    GWImageCard: typeof import('./src/components/GWImageCard.vue')['default']
    GWLinkCard: typeof import('./src/components/GWLinkCard.vue')['default']
    GWPreviewImage: typeof import('./src/components/GWPreviewImage.vue')['default']
    GWPreviewVideo: typeof import('./src/components/GWPreviewVideo.vue')['default']
    GWResourceSearch: typeof import('./src/components/GWResourceSearch.vue')['default']
    GWTitleImageCard: typeof import('./src/components/GWTitleImageCard.vue')['default']
    GWVirtualWaterFall: typeof import('./src/components/GWVirtualWaterFall.vue')['default']
    GWWaterFall: typeof import('./src/components/GWWaterFall.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Template: typeof import('./src/components/Template.vue')['default']
  }
}
