/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BLCol: typeof import('./src/components/BLCol.vue')['default']
    BLRow: typeof import('./src/components/BLRow.vue')['default']
    BLTag: typeof import('./src/components/BLTag.vue')['default']
    copy: typeof import('./src/components/GWImageCard copy.vue')['default']
    DayNight: typeof import('./src/components/DayNight.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElTree: typeof import('element-plus/es')['ElTree']
    ElWatermark: typeof import('element-plus/es')['ElWatermark']
    FsEstimatedVirtualList: typeof import('./src/components/FsEstimatedVirtualList.vue')['default']
    FsVirtualList: typeof import('./src/components/FsVirtualList.vue')['default']
    FsVirtualWaterFall: typeof import('./src/components/FsVirtualWaterFall.vue')['default']
    GWHeader: typeof import('./src/components/GWHeader.vue')['default']
    GWImageCard: typeof import('./src/components/GWImageCard.vue')['default']
    GWImagePreview: typeof import('./src/components/GWImagePreview.vue')['default']
    GWLinkCard: typeof import('./src/components/GWLinkCard.vue')['default']
    GWTitleImageCard: typeof import('./src/components/GWTitleImageCard.vue')['default']
    GWVirtualWaterFall: typeof import('./src/components/GWVirtualWaterFall.vue')['default']
    GWWaterFall: typeof import('./src/components/GWWaterFall.vue')['default']
    ListItem: typeof import('./src/components/ListItem.vue')['default']
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    Template: typeof import('./src/components/Template.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
